charaters_name = {
    '易书元': 'Dịch Thư Nguyên', 
    '大爷': 'Đại thúc', 
    '入': 'nhập',
    '阿狗': 'A Cẩu',
    '不过': 'nhưng',
    '雪蟒': 'Tuyết Mãng ',
    '清心诀': 'Thanh Tâm Quyết',
    '阿飞': 'A Phi',
    '篝火': 'đống lửa',
    '但他' : 'nhưng hắn',
    '大伯': 'Đại Bá',
    '西河': 'Tây Hà',
    '易勇安': 'Dịch Dũng An',
    '物是人非': 'cảnh còn người mất',
    '你去': 'ngươi đi',
    '我': 'ta',
    '同心楼': 'Đồng Tâm Lâu',
    '主簿': 'chủ bộ',
    '落款': 'lạc khoản',
    '我们': 'chúng ta',
    '休沐': 'nghỉ phép',
    '告': 'cáo trạng',
    '贾云通': 'Giả Vân Thông',
    '人微言轻': 'thấp cổ bé họng',
    '捕头': 'bộ đầu',
    '大理寺': 'Đại Lý Tự',
    '有劳': 'làm phiền',
    '竹罐': 'bình trúc',
    '南山': 'Nam Sơn',
    '手无缚鸡之力': ' tay trói gà không chặt',
    '山神': 'Sơn Thần',
    '茶棚': 'quán trà',
    '舅舅': 'Cữu cữu',
    '山南岗': 'Sơn Nam Cương',
    '包袱': 'hành lý',
    '天界': 'Thiên Giới',
    '黄公': 'Hoàng Công',
    '娃娃': 'Bé con',
    '易某': 'Dịch mỗ',
    '土地': 'thổ địa',
    '黄宏川' : 'Hoàng Hồng Xuyên',
    '文案': 'văn án',
    '告辞': 'cáo từ',
    }
