charaters_name = {
    '易书元': 'Dịch Thư Nguyên', 
    '大爷': 'Đại thúc', 
    '入': 'nhập',
    '阿狗': 'A Cẩu',
    '不过': 'nhưng',
    '雪蟒': 'Tuyết Mãng ',
    '清心诀': 'Thanh Tâm Quyết',
    '阿飞': 'A Phi',
    '篝火': 'đống lửa',
    '但他' : 'nhưng hắn',
    '大伯': 'Đại Bá',
    '西河': 'Tây Hà',
    '易勇安': 'Dịch Dũng An',
    '物是人非': 'cảnh còn người mất',
    '你去': 'ngươi đi',
    '我': 'ta',
    '同心楼': 'Đồng Tâm Lâu',
    '主簿': 'chủ bộ',
    '落款': 'lạc khoản',
    '我们': 'chúng ta',
    '休沐': 'nghỉ phép',
    '告': 'cáo trạng',
    '贾云通': 'Giả Vân Thông',
    '人微言轻': 'thấp cổ bé họng',
    '捕头': 'bộ đầu',
    '大理寺': 'Đại Lý Tự',
    '有劳': 'làm phiền',
    '竹罐': 'bình trúc',
    '南山': 'Nam Sơn',
    '手无缚鸡之力': ' tay trói gà không chặt',
    '山神': 'Sơn Thần',
    '茶棚': 'quán trà',
    '舅舅': 'Cữu cữu',
    '山南岗': 'Sơn Nam Cương',
    '包袱': 'hành lý',
    '天界': 'Thiên Giới',
    '黄公': 'Hoàng Công',
    '娃娃': 'Bé con',
    '易某': 'Dịch mỗ',
    '土地': 'thổ địa',
    '黄宏川' : 'Hoàng Hồng Xuyên',
    '文案': 'văn án',
    '告辞': 'cáo từ',
    '簸箕': 'ki hốt rác',
    '城隍':'Thành Hoàng',
    '鬼神': 'quỷ thần',
    '有何贵干': 'là có chuyện gì',
    '阴司': 'Âm Ti',
    '窝头': 'bánh ngô'
    '醉宾楼: Túy Tân Lâu',
    '进入了': 'tiến vào',
    '在下': 'Tại hạ',
    '向常青':'Hướng Thường Thanh',
    '馄饨': 'mì hoành thánh',
    '鬼魂': 'Quỷ Hồn',
    '乌木': 'Ô Mộc',
    '障眼法': 'Chướng Nhãn pháp',
    '牢头': 'cai tù',
    '给我出来': 'đi ra cho ta',
    '你看': 'ngài xem',
    '告诉你': 'nói cho ngươi biết',
    '告诉我': 'nói cho ta biết',
    '救你': 'cứu ngươi',
    '我就告退了': 'ta liền cáo lui',
    '告退了': 'cáo lui',
    '校场': 'võ đài',
    '先生': 'tiên sinh',
    '说笑了': 'nói đùa',
    }
